{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2014-7143"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "Python Twisted 14.0 trustRoot is not respected in HTTP client"
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-295"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "http://www.openwall.com/lists/oss-security/2014/09/22/2",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://www.openwall.com/lists/oss-security/2014/09/22/2"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143"
				},
				{
					"name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135"
				},
				{
					"name": "https://security-tracker.debian.org/tracker/CVE-2014-7143",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://security-tracker.debian.org/tracker/CVE-2014-7143"
				},
				{
					"name": "http://www.openwall.com/lists/oss-security/2014/09/22/2",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://www.openwall.com/lists/oss-security/2014/09/22/2"
				},
				{
					"name": "https://security-tracker.debian.org/tracker/CVE-2014-7143",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://security-tracker.debian.org/tracker/CVE-2014-7143"
				},
				{
					"name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "NONE",
				"baseScore": 5,
				"confidentialityImpact": "NONE",
				"integrityImpact": "PARTIAL",
				"vectorString": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "NONE",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "HIGH",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:twistedmatrix:twisted:14.0.0:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T02:16Z",
	"publishedDate": "2019-11-12T14:15Z"
}
