{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2024-39329"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://docs.djangoproject.com/en/dev/releases/security/",
					"url": "https://docs.djangoproject.com/en/dev/releases/security/"
				},
				{
					"name": "https://groups.google.com/forum/#%21forum/django-announce",
					"url": "https://groups.google.com/forum/#%21forum/django-announce"
				},
				{
					"name": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
				}
			]
		}
	},
	"impact": {},
	"configurations": {
		"CVE_data_version": "4.0"
	},
	"lastModifiedDate": "2024-07-10T05:15Z",
	"publishedDate": "2024-07-10T05:15Z"
}
