{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "security@jfrog.com",
			"ID": "CVE-2024-27133"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-79"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/",
					"url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/"
				},
				{
					"name": "https://github.com/mlflow/mlflow/pull/10893",
					"url": "https://github.com/mlflow/mlflow/pull/10893"
				}
			]
		}
	},
	"impact": {},
	"configurations": {
		"CVE_data_version": "4.0"
	},
	"lastModifiedDate": "2024-02-26T13:42Z",
	"publishedDate": "2024-02-23T22:15Z"
}
