{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "secalert@redhat.com",
			"ID": "CVE-2018-14647"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "Python's elementtree C accelerator failed to initialise Expat's hash salt during initialization. This could make it easy to conduct denial of service attacks against Expat by constructing an XML document that would cause pathological hash collisions in Expat's internal data structures, consuming large amounts CPU and RAM. The vulnerability exists in Python versions 3.7.0, 3.6.0 through 3.6.6, 3.5.0 through 3.5.6, 3.4.0 through 3.4.9, 2.7.0 through 2.7.15."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-909"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "openSUSE-SU-2020:0086",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
				},
				{
					"name": "105396",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securityfocus.com/bid/105396"
				},
				{
					"name": "1041740",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securitytracker.com/id/1041740"
				},
				{
					"name": "RHSA-2019:1260",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:1260"
				},
				{
					"name": "RHSA-2019:2030",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:2030"
				},
				{
					"name": "RHSA-2019:3725",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3725"
				},
				{
					"name": "https://bugs.python.org/issue34623",
					"tags": [
						"Issue Tracking",
						"Patch",
						"Vendor Advisory"
					],
					"url": "https://bugs.python.org/issue34623"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647"
				},
				{
					"name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
					"url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
				},
				{
					"name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
				},
				{
					"name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-1] python3.4 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html"
				},
				{
					"name": "FEDORA-2019-0c91ce7b3c",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RBJCB2HWOJLP3L7CUQHJHNBHLSVOXJE5/"
				},
				{
					"name": "USN-3817-1",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://usn.ubuntu.com/3817-1/"
				},
				{
					"name": "USN-3817-2",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://usn.ubuntu.com/3817-2/"
				},
				{
					"name": "DSA-4306",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://www.debian.org/security/2018/dsa-4306"
				},
				{
					"name": "DSA-4307",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://www.debian.org/security/2018/dsa-4307"
				},
				{
					"name": "openSUSE-SU-2020:0086",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
				},
				{
					"name": "DSA-4307",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://www.debian.org/security/2018/dsa-4307"
				},
				{
					"name": "DSA-4306",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://www.debian.org/security/2018/dsa-4306"
				},
				{
					"name": "USN-3817-2",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://usn.ubuntu.com/3817-2/"
				},
				{
					"name": "USN-3817-1",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://usn.ubuntu.com/3817-1/"
				},
				{
					"name": "FEDORA-2019-0c91ce7b3c",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RBJCB2HWOJLP3L7CUQHJHNBHLSVOXJE5/"
				},
				{
					"name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-1] python3.4 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html"
				},
				{
					"name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
				},
				{
					"name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
					"url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647"
				},
				{
					"name": "https://bugs.python.org/issue34623",
					"tags": [
						"Issue Tracking",
						"Patch",
						"Vendor Advisory"
					],
					"url": "https://bugs.python.org/issue34623"
				},
				{
					"name": "RHSA-2019:3725",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3725"
				},
				{
					"name": "RHSA-2019:2030",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:2030"
				},
				{
					"name": "RHSA-2019:1260",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:1260"
				},
				{
					"name": "1041740",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securitytracker.com/id/1041740"
				},
				{
					"name": "105396",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securityfocus.com/bid/105396"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "PARTIAL",
				"baseScore": 5,
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "3.5.6",
						"versionStartIncluding": "3.5.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "2.7.15",
						"versionStartIncluding": "2.7.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "3.4.9",
						"versionStartIncluding": "3.4.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "3.6.6",
						"versionStartIncluding": "3.6.0",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:12.04:*:*:*:esm:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:esm:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:30:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:opensuse:leap:15.1:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T03:49Z",
	"publishedDate": "2018-09-25T00:29Z"
}
