{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2018-1000117"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "Python Software Foundation CPython version From 3.2 until 3.6.4 on Windows contains a Buffer Overflow vulnerability in os.symlink() function on Windows that can result in Arbitrary code execution, likely escalation of privilege. This attack appears to be exploitable via a python script that creates a symlink with an attacker controlled name or location. This vulnerability appears to have been fixed in 3.7.0 and 3.6.5."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-120"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://github.com/python/cpython/pull/5989",
					"refsource": "CONFIRM",
					"tags": [
						"Issue Tracking",
						"Patch",
						"Vendor Advisory"
					],
					"url": "https://github.com/python/cpython/pull/5989"
				},
				{
					"name": "https://bugs.python.org/issue33001",
					"refsource": "CONFIRM",
					"tags": [
						"Issue Tracking",
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://bugs.python.org/issue33001"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "LOCAL",
				"authentication": "NONE",
				"availabilityImpact": "COMPLETE",
				"baseScore": 7.2,
				"confidentialityImpact": "COMPLETE",
				"integrityImpact": "COMPLETE",
				"vectorString": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
				"version": "2.0"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 10,
			"severity": "HIGH"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "LOCAL",
				"availabilityImpact": "HIGH",
				"baseScore": 6.7,
				"baseSeverity": "MEDIUM",
				"confidentialityImpact": "HIGH",
				"integrityImpact": "HIGH",
				"privilegesRequired": "HIGH",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 0.8,
			"impactScore": 5.9
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"children": [
					{
						"cpe_match": [
							{
								"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
								"versionEndExcluding": "3.4.9",
								"versionStartIncluding": "3.2.0",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
								"versionEndExcluding": "3.5.6",
								"versionStartIncluding": "3.5.0",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
								"versionEndExcluding": "3.6.5",
								"versionStartIncluding": "3.6.0",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:beta1:*:*:*:*:*:*",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:beta2:*:*:*:*:*:*",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:beta3:*:*:*:*:*:*",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:beta4:*:*:*:*:*:*",
								"vulnerable": true
							},
							{
								"cpe23Uri": "cpe:2.3:a:python:python:3.7.0:beta5:*:*:*:*:*:*",
								"vulnerable": true
							}
						],
						"operator": "OR"
					},
					{
						"cpe_match": [
							{
								"cpe23Uri": "cpe:2.3:o:microsoft:windows:*:*:*:*:*:*:*:*"
							}
						],
						"operator": "OR"
					}
				],
				"operator": "AND"
			}
		]
	},
	"lastModifiedDate": "2022-07-05T18:56Z",
	"publishedDate": "2018-03-07T14:29Z"
}
