{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "talos-cna@cisco.com",
			"ID": "CVE-2019-5010"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-476"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "openSUSE-SU-2020:0086",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
				},
				{
					"name": "openSUSE-SU-2020:0086",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
				},
				{
					"name": "RHSA-2019:3520",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3520"
				},
				{
					"name": "RHSA-2019:3520",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3520"
				},
				{
					"name": "RHSA-2019:3725",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3725"
				},
				{
					"name": "RHSA-2019:3725",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:3725"
				},
				{
					"name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
					"url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
				},
				{
					"name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
					"url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
				},
				{
					"name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
				},
				{
					"name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
				},
				{
					"name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
				},
				{
					"name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
				},
				{
					"name": "GLSA-202003-26",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://security.gentoo.org/glsa/202003-26"
				},
				{
					"name": "GLSA-202003-26",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://security.gentoo.org/glsa/202003-26"
				},
				{
					"name": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758",
					"tags": [
						"Exploit",
						"Third Party Advisory"
					],
					"url": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758"
				},
				{
					"name": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758",
					"tags": [
						"Exploit",
						"Third Party Advisory"
					],
					"url": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "PARTIAL",
				"baseScore": 5,
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "3.7.3",
						"versionStartIncluding": "3.7.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "3.6.9",
						"versionStartIncluding": "3.6.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "3.5.7",
						"versionStartIncluding": "3.5.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "2.7.16",
						"versionStartIncluding": "2.7.0",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "3.4.10",
						"versionStartIncluding": "3.4.0",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:opensuse:leap:15.1:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_eus:8.1:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_eus:8.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_tus:8.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_aus:8.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_tus:8.4:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_eus:8.4:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_aus:8.4:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_aus:8.6:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server_tus:8.6:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_eus:8.6:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T04:44Z",
	"publishedDate": "2019-10-31T21:15Z"
}
