{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2016-10321"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "web2py before 2.14.6 does not properly check if a host is denied before verifying passwords, allowing a remote attacker to perform brute-force attacks."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-254"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426",
					"tags": [
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426"
				},
				{
					"name": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426",
					"tags": [
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426"
				},
				{
					"name": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919"
				},
				{
					"name": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919"
				},
				{
					"name": "USN-4030-1",
					"url": "https://usn.ubuntu.com/4030-1/"
				},
				{
					"name": "USN-4030-1",
					"url": "https://usn.ubuntu.com/4030-1/"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "NONE",
				"baseScore": 5,
				"confidentialityImpact": "PARTIAL",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 9.8,
				"baseSeverity": "CRITICAL",
				"confidentialityImpact": "HIGH",
				"integrityImpact": "HIGH",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
				"version": "3.0"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 5.9
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:web2py:web2py:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "2.14.5",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T02:43Z",
	"publishedDate": "2017-04-10T14:59Z"
}
