{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2011-4137"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-399"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"tags": [
						"Patch"
					],
					"url": "http://openwall.com/lists/oss-security/2011/09/11/1"
				},
				{
					"name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"tags": [
						"Patch"
					],
					"url": "http://openwall.com/lists/oss-security/2011/09/13/2"
				},
				{
					"name": "[oss-security] 20110916 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"url": "http://openwall.com/lists/oss-security/2011/09/15/5"
				},
				{
					"name": "46614",
					"url": "http://secunia.com/advisories/46614"
				},
				{
					"name": "DSA-2332",
					"url": "http://www.debian.org/security/2011/dsa-2332"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=737366",
					"tags": [
						"Patch"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366"
				},
				{
					"name": "openSUSE-SU-2012:0653",
					"url": "https://hermes.opensuse.org/messages/14700881"
				},
				{
					"name": "https://www.djangoproject.com/weblog/2011/sep/09/",
					"tags": [
						"Patch",
						"Vendor Advisory"
					],
					"url": "https://www.djangoproject.com/weblog/2011/sep/09/"
				},
				{
					"name": "https://www.djangoproject.com/weblog/2011/sep/10/127/",
					"tags": [
						"Patch"
					],
					"url": "https://www.djangoproject.com/weblog/2011/sep/10/127/"
				},
				{
					"name": "[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"tags": [
						"Patch"
					],
					"url": "http://openwall.com/lists/oss-security/2011/09/11/1"
				},
				{
					"name": "https://www.djangoproject.com/weblog/2011/sep/10/127/",
					"tags": [
						"Patch"
					],
					"url": "https://www.djangoproject.com/weblog/2011/sep/10/127/"
				},
				{
					"name": "https://www.djangoproject.com/weblog/2011/sep/09/",
					"tags": [
						"Patch",
						"Vendor Advisory"
					],
					"url": "https://www.djangoproject.com/weblog/2011/sep/09/"
				},
				{
					"name": "openSUSE-SU-2012:0653",
					"url": "https://hermes.opensuse.org/messages/14700881"
				},
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=737366",
					"tags": [
						"Patch"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366"
				},
				{
					"name": "DSA-2332",
					"url": "http://www.debian.org/security/2011/dsa-2332"
				},
				{
					"name": "46614",
					"url": "http://secunia.com/advisories/46614"
				},
				{
					"name": "[oss-security] 20110916 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"url": "http://openwall.com/lists/oss-security/2011/09/15/5"
				},
				{
					"name": "[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws",
					"tags": [
						"Patch"
					],
					"url": "http://openwall.com/lists/oss-security/2011/09/13/2"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "PARTIAL",
				"baseScore": 5,
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "1.2.6",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.5:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:0.95:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.3:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.1.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.0.1:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.1:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.1:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.4:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:0.91:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.0.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.3:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.3:alpha1:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.1.3:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.1:2:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:0.95.1:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:0.96:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.3:alpha2:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.1.0:*:*:*:*:*:*:*",
						"vulnerable": true
					},
					{
						"cpe23Uri": "cpe:2.3:a:djangoproject:django:1.2.2:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T01:31Z",
	"publishedDate": "2011-10-19T10:55Z"
}
