{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "secalert@redhat.com",
			"ID": "CVE-2021-20275"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "A flaw was found in privoxy before 3.0.32. A invalid read of size two may occur in chunked_body_is_complete() leading to denial of service."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-125"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=1936666",
					"refsource": "MISC",
					"tags": [
						"Issue Tracking",
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1936666"
				},
				{
					"name": "https://www.privoxy.org/announce.txt",
					"refsource": "MISC",
					"tags": [
						"Release Notes",
						"Vendor Advisory"
					],
					"url": "https://www.privoxy.org/announce.txt"
				},
				{
					"name": "[debian-lts-announce] 20210309 [SECURITY] [DLA 2587-1] privoxy security update",
					"refsource": "MLIST",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00009.html"
				},
				{
					"name": "GLSA-202107-16",
					"refsource": "GENTOO",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://security.gentoo.org/glsa/202107-16"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "PARTIAL",
				"baseScore": 5,
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:privoxy:privoxy:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "3.0.32",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2022-08-05T18:06Z",
	"publishedDate": "2021-03-09T14:15Z"
}
